### ISSUE TITLE
Desarrollar la página de negociación

### ISSUE THREAD

**Issue by arejula27** [ZaragozaEnJuego/client#16]
Implementar la página de negociación exceptuando el chat.

**Comment by ibon-sk** [comment]
### Reinterpretación de la negociación tras 1ª reunión con el tutor del proyecto.

La negociación pasa a consistir exclusivamente en ofertas aceptables o rechazables por el usuario propietario. El usuario que crea la oferta puede cancelarla en cualquier momento de su ciclo vital (antes de ser aceptada o rechazada).

Se desestima el desarrollo de un chat entre los usuarios involucrados.

**Comment by ibon-sk** [comment]
Se deben corregir los siguientes fallos en la visualización de la página en vistas más pequeñas, esto es, cuando el formato de dos columnas pasa a una sola :

- [x] Las ofertas no se pueden visualizar correctamente. Los elementos de la oferta deben hacerse más pequeños conforme se hace más pequeño el volumen máximo de cada oferta

- [x] El scroll vertical de la página hace que el header principal se superponga sobre los elementos de la pantalla, cuando debe mantenerse fijo en la misma.
